# Generated by Django 5.1.2 on 2024-11-14 15:02

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repository", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField()),
            ],
        ),
    ]
