# Generated by Django 5.1.2 on 2025-01-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_project_alter_workflowresult_options_and_more"),
        ("embeddings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embedding",
            name="repository",
        ),
        migrations.AddField(
            model_name="embedding",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
            ),
        ),
    ]
