version: "3.9"

services:
  db:
    image: ankane/pgvector
    ports:
     - 63045:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./vector/scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data:rw

  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]


volumes:
  db-data: { }