services:
  labs-db:
    container_name: labs-db
    image: pgvector/pgvector:pg16
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres

  api:
    env_file: .env.local
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - labs-db
      - redis
    volumes:
      - api_logs:/app/logs
      - ./labs/:/app/
      - ${REPOSITORIES_PATH}:/repositories/

  worker:
    env_file: .env.local
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A config worker --beat --scheduler redbeat.RedBeatScheduler --loglevel=INFO --concurrency=1
    depends_on:
      - redis
      - labs-db
    volumes:
      - worker_logs:/app/logs
      - ./labs/:/app/
      - ${REPOSITORIES_PATH}:/repositories/

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flower:
    image: mher/flower:latest
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis

  promtail:
    env_file: .env.local
    image: grafana/promtail:3.1.1
    volumes:
      - api_logs:/var/log/api
      - worker_logs:/var/log/worker
      - ./logs/:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
    entrypoint: >
      /bin/bash -c "/usr/bin/promtail -config.expand-env=true -config.file /etc/promtail/config.yml"

volumes:
  api_logs:
  worker_logs:
  ollama:
