services:
  labs-db:
    container_name: labs-db
    image: pgvector/pgvector:pg16
    ports:
     - ${DATABASE_PORT}:5432
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./database_scripts:/docker-entrypoint-initdb.d

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./src/config/litellm.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]
