[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "labs"
version = "0.0.1"
description = "Runtime Labs"
authors = [
  { name = "runtimerevolution" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.11"
dependencies = ["pyautogen"]

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.ruff.lint.isort]
known_first_party = ["labs"]
force_sort_within_sections = true

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tool.pixi.pypi-dependencies]
labs = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "==3.11.9"
python-dotenv = ">=1.0.1,<1.1"
git = ">=2.45.2,<2.46"
ipython = ">=8.26.0,<8.27"
gitpython = ">=3.1.43,<3.2"
