model_list:
  - model_name: llm-model
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: llm-model
    litellm_params:
      model: cohere/command-light
      api_key: os.environ/COHERE_API_KEY
  # - model_name: llm-model
  #   litellm_params:
  #     model: gemini/gemini-pro
  #     api_key: os.environ/GEMINI_API_KEY
  - model_name: llm-model
    litellm_params:
      model: groq/llama3-8b-8192
      api_key: os.environ/GROQ_API_KEY

