# Generated by Django 5.1.2 on 2024-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("OPENAI", "OpenAI"), ("OLLAMA", "Ollama")]),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VectorizerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vectorizer_type",
                    models.CharField(
                        choices=[
                            ("CHUNK_VECTORIZER", "File chunks"),
                            ("PYTHON_VECTORIZER", "Python structured"),
                        ]
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vectorizer",
                "verbose_name_plural": "Vectorizers",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(choices=[("EMBEDDING", "Embedding"), ("LLM", "LLM")]),
                ),
                (
                    "provider",
                    models.CharField(choices=[("OPENAI", "OpenAI"), ("OLLAMA", "Ollama")]),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "model_name"],
                        name="core_model_provide_63062e_idx",
                    )
                ],
            },
        ),
    ]
