# Generated by Django 5.1.2 on 2024-11-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("OPENAI", "OPENAI"), ("OLLAMA", "OLLAMA")]),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(choices=[("EMBEDDING", "EMBEDDING"), ("LLM", "LLM")]),
                ),
                (
                    "provider",
                    models.CharField(choices=[("OPENAI", "OPENAI"), ("OLLAMA", "OLLAMA")]),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "model_name"],
                        name="core_config_provide_5432fd_idx",
                    )
                ],
            },
        ),
    ]
