# Generated by Django 5.1.2 on 2025-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.CharField(max_length=255)),
                ("embed_model", models.CharField(max_length=255, null=True)),
                ("prompt_model", models.CharField(max_length=255, null=True)),
                ("embeddings", models.TextField(null=True)),
                ("context", models.TextField(null=True)),
                ("llm_response", models.TextField(null=True)),
                ("modified_files", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
