# Generated by Django 5.1.2 on 2025-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_workflowresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowresult",
            name="pre_commit_error",
            field=models.TextField(null=True),
        ),
    ]
