# Generated by Django 5.1.2 on 2025-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workflowresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='embeddings',
            field=models.JSONField(null=True),
        ),
    ]
