# Generated by Django 5.1.2 on 2025-01-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_workflowresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.TextField(
                        help_text="It should include additional information to help guide the model's behavior and \n        understanding of its role."
                    ),
                ),
                (
                    "instruction",
                    models.TextField(
                        help_text='It should include guidelines on what is expected in the generated code, \n        such as "avoid complexity" or "minimize the code".'
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
            },
        ),
    ]
