# Generated by Django 5.1.2 on 2025-01-27 15:38

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_workflowresult_pre_commit_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("path", models.CharField(max_length=255, unique=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="workflowresult",
            options={
                "verbose_name": "Workflow result",
                "verbose_name_plural": "Workflow results",
            },
        ),
        migrations.RemoveField(
            model_name="model",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="model",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="variable",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="variable",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="vectorizermodel",
            name="active",
        ),
        migrations.RemoveField(
            model_name="vectorizermodel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="vectorizermodel",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="model",
            name="provider",
            field=models.CharField(
                choices=[
                    ("NO_PROVIDER", "No provider"),
                    ("OPENAI", "OpenAI"),
                    ("OLLAMA", "Ollama"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="provider",
            field=models.CharField(
                choices=[
                    ("NO_PROVIDER", "No provider"),
                    ("OPENAI", "OpenAI"),
                    ("OLLAMA", "Ollama"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="vectorizermodel",
            name="vectorizer_type",
            field=models.CharField(
                choices=[
                    ("CHUNK_VECTORIZER", "File chunks"),
                    ("PYTHON_VECTORIZER", "Python structured"),
                ],
                default=core.models.Variable.get_default_vectorizer_value,
            ),
        ),
        migrations.AddField(
            model_name="vectorizermodel",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="workflowresult",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
            ),
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.TextField(
                        default=core.models.Variable.get_default_persona_value,
                        help_text="It should include additional information to help guide the model's behavior and \n        understanding of its role.",
                    ),
                ),
                (
                    "instruction",
                    models.TextField(
                        default=core.models.Variable.get_default_instruction_value,
                        help_text='It should include guidelines on what is expected in the generated code, \n        such as "avoid complexity" or "minimize the code".',
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
            },
        ),
    ]
