# Generated by Django 5.1.2 on 2025-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workflowresult_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='context',
            field=models.JSONField(null=True),
        ),
    ]
