# Generated by Django 5.1.2 on 2025-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_alter_workflowresult_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="provider",
            field=models.CharField(
                choices=[
                    ("NO_PROVIDER", "No provider"),
                    ("OPENAI", "OpenAI"),
                    ("OLLAMA", "Ollama"),
                    ("GEMINI", "Gemini"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="provider",
            field=models.CharField(
                choices=[
                    ("NO_PROVIDER", "No provider"),
                    ("OPENAI", "OpenAI"),
                    ("OLLAMA", "Ollama"),
                    ("GEMINI", "Gemini"),
                ]
            ),
        ),
    ]
