# Generated by Django 5.1.2 on 2025-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workflowresult_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='llm_response',
            field=models.TextField(null=True),
        ),
    ]
