# Generated by Django 5.1.5 on 2025-02-25 10:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_model_provider_alter_variable_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="variable",
            unique_together={("provider", "name")},
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("active", True),
                    ("model_type", core.models.ModelTypeEnum["EMBEDDING"]),
                ),
                fields=("model_type",),
                name="unique_active_embedding",
            ),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("active", True), ("model_type", core.models.ModelTypeEnum["LLM"])
                ),
                fields=("model_type",),
                name="unique_active_llm",
            ),
        ),
    ]
