# Generated by Django 5.1.5 on 2025-02-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_model_unique_active_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="provider",
            field=models.CharField(
                choices=[
                    ("NO_PROVIDER", "No provider"),
                    ("OPENAI", "OpenAI"),
                    ("OLLAMA", "Ollama"),
                    ("GEMINI", "Gemini"),
                    ("ANTHROPIC", "Anthropic"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="provider",
            field=models.CharField(
                choices=[
                    ("NO_PROVIDER", "No provider"),
                    ("OPENAI", "OpenAI"),
                    ("OLLAMA", "Ollama"),
                    ("GEMINI", "Gemini"),
                    ("ANTHROPIC", "Anthropic"),
                ]
            ),
        ),
    ]
