# Generated by Django 5.1.5 on 2025-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_model_provider_alter_variable_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="variable",
            unique_together={("provider", "name")},
        ),
    ]
