# Generated by Django 5.1.5 on 2025-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_embeddingmodel_llmmodel_delete_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowresult",
            name="embeddings_tokens",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
