# Generated by Django 5.1.5 on 2025-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_workflowresult_embeddings_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowresult",
            name="prompt_tokens",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
