# Generated by Django 5.1.7 on 2025-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_workflowresult_prompt_tokens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowresult",
            name="prompt_tokens",
        ),
        migrations.AddField(
            model_name="workflowresult",
            name="llm_tokens",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
