# Generated by Django 5.1.2 on 2024-10-18 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("llm_model", models.TextField(blank=True, null=True)),
                ("key", models.TextField(unique=True)),
                ("value", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "llm_model"],
                        name="config_conf_config__4d9363_idx",
                    )
                ],
            },
        ),
    ]
