# Generated by Django 5.1.2 on 2024-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="config",
            new_name="config_conf_key_45248a_idx",
            old_name="config_conf_config__4d9363_idx",
        ),
        migrations.AlterField(
            model_name="config",
            name="key",
            field=models.TextField(
                choices=[
                    ("ACTIVELOOP_TOKEN", "ACTIVELOOP_TOKEN"),
                    ("ANTHROPIC_API_KEY", "ANTHROPIC_API_KEY"),
                    ("ANYSCALE_API_KEY", "ANYSCALE_API_KEY"),
                    ("COHERE_API_KEY", "COHERE_API_KEY"),
                    ("GEMINI_API_KEY", "GEMINI_API_KEY"),
                    ("GROQ_API_KEY", "GROQ_API_KEY"),
                    ("HUGGINGFACE_API_KEY", "HUGGINGFACE_API_KEY"),
                    ("LITELLM_API_KEY", "LITELLM_API_KEY"),
                    ("LITELLM_MASTER_KEY", "LITELLM_MASTER_KEY"),
                    ("MISTRAL_API_KEY", "MISTRAL_API_KEY"),
                    ("OPENAI_API_KEY", "OPENAI_API_KEY"),
                ],
                unique=True,
            ),
        ),
    ]
