model_list:
  - model_name: llm-model
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: llm-model
    litellm_params:
      model: cohere/command-r
      api_key: os.environ/COHERE_API_KEY
  # - model_name: llm-model
  #   litellm_params:
  #     model: gemini/gemini-pro
  #     api_key: os.environ/GEMINI_API_KEY
  - model_name: llm-model
    litellm_params:
      model: groq/llama3-8b-8192
      api_key: os.environ/GROQ_API_KEY
  - model_name: llm-model
    litellm_params:
      model: huggingface/tiiuae/falcon-7b-instruct
      api_key: os.environ/HUGGINGFACE_API_KEY
  - model_name: llm-model
    litellm_params:
      model: anthropic/claude-3-5-sonnet
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: llm-model
    litellm_params:
      model: mistral/open-mistral-7b
      api_key: os.environ/MISTRAL_API_KEY
